In [1]:
import requests

r = requests.get("https://gamma-api.polymarket.com/events?closed=false")
response = r.json()

response

[{'id': '16084',
  'ticker': 'fed-rate-hike-in-2025',
  'slug': 'fed-rate-hike-in-2025',
  'title': 'Fed rate hike in 2025?',
  'description': 'This market will resolve to “Yes” if the upper bound of the target federal funds rate is increased at any point between January 1, 2025 and the Fed\'s December 2025 meeting, currently scheduled for December 9-10. Otherwise, this market will resolve to “No”.\n\nThis market may not resolve to "No" until the Fed has released its rate changes information following its December meeting.\n\nThe primary resolution source for this market will be the official website of the Federal Reserve (https://www.federalreserve.gov/monetarypolicy/openmarket.htm), however a consensus of credible reporting may also be used.',
  'startDate': '2024-12-29T22:50:44.013518Z',
  'creationDate': '2024-12-29T22:50:44.013516Z',
  'endDate': '2025-12-10T12:00:00Z',
  'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-the-fed-raise-interest-rates-in-2025-PQTEYZMvmAGr.jpg',
  'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-the-fed-raise-interest-rates-in-2025-PQTEYZMvmAGr.jpg',
  'active': True,
  'closed': False,
  'archived': False,
  'new': False,
  'featured': False,
  'restricted': True,
  'liquidity': 60848.22599,
  'volume': 736030.554114,
  'openInterest': 0,
  'createdAt': '2024-12-29T17:37:59.684632Z',
  'updatedAt': '2025-11-08T19:49:58.219481Z',
  'competitive': 0.8086151475045429,
  'volume24hr': 6078.04,
  'volume1wk': 60986.63148599999,
  'volume1mo': 185156.70952700006,
  'volume1yr': 736010.5541139981,
  'enableOrderBook': True,
  'liquidityClob': 60848.22599,
  'commentCount': 21,
  'markets': [{'id': '516706',
    'question': 'Fed rate hike in 2025?',
    'conditionId': '0x4319532e181605cb15b1bd677759a3bc7f7394b2fdf145195b700eeaedfd5221',
    'slug': 'fed-rate-hike-in-2025',
    'resolutionSource': '',
    'endDate': '2025-12-10T12:00:00Z',
    'liquidity': '60848.22599',
    'startDate': '2024-12-29T22:50:33.584839Z',
    'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-the-fed-raise-interest-rates-in-2025-PQTEYZMvmAGr.jpg',
    'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/will-the-fed-raise-interest-rates-in-2025-PQTEYZMvmAGr.jpg',
    'description': 'This market will resolve to “Yes” if the upper bound of the target federal funds rate is increased at any point between January 1, 2025 and the Fed\'s December 2025 meeting, currently scheduled for December 9-10. Otherwise, this market will resolve to “No”.\n\nThis market may not resolve to "No" until the Fed has released its rate changes information following its December meeting.\n\nThe primary resolution source for this market will be the official website of the Federal Reserve (https://www.federalreserve.gov/monetarypolicy/openmarket.htm), however a consensus of credible reporting may also be used.',
    'outcomes': '["Yes", "No"]',
    'outcomePrices': '["0.0135", "0.9865"]',
    'volume': '736030.554114',
    'active': True,
    'closed': False,
    'marketMakerAddress': '',
    'createdAt': '2024-12-29T17:38:00.916304Z',
    'updatedAt': '2025-11-08T19:52:19.294139Z',
    'new': False,
    'featured': False,
    'submitted_by': '0x91430CaD2d3975766499717fA0D66A78D814E5c5',
    'archived': False,
    'resolvedBy': '0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74',
    'restricted': True,
    'groupItemTitle': '',
    'groupItemThreshold': '0',
    'questionID': '0x8428884817cbc26422ec451101fcedfc5995907a8df6e5905bc29cd30d2867e7',
    'enableOrderBook': True,
    'orderPriceMinTickSize': 0.001,
    'orderMinSize': 5,
    'volumeNum': 736030.554114,
    'liquidityNum': 60848.22599,
    'endDateIso': '2025-12-10',
    'startDateIso': '2024-12-29',
    'hasReviewedDates': True,
    'volume24hr': 6078.04,
    'volume1wk': 60986.63148599999,
    'volume1mo': 185156.70952700006,
    'volume1yr': 736010.5541139981,
    'clobTokenIds': '["60487116984468020978247225474488676749601001829886755968952521846780452448915", "81104637750588840860328515305303028259865221573278091453716127842023614249200"]',
    'umaBond': '500',
    'umaReward': '5',
    'volume24hrClob': 6078.04,
    'volume1wkClob': 60986.63148599999,
    'volume1moClob': 185156.70952700006,
    'volume1yrClob': 736010.5541139981,
    'volumeClob': 736030.554114,
    'liquidityClob': 60848.22599,
    'acceptingOrders': True,
    'negRisk': False,
    'ready': False,
    'funded': False,
    'acceptingOrdersTimestamp': '2024-12-29T22:49:15Z',
    'cyom': False,
    'competitive': 0.8086151475045429,
    'pagerDutyNotificationEnabled': False,
    'approved': True,
    'rewardsMinSize': 100,
    'rewardsMaxSpread': 3.5,
    'spread': 0.001,
    'oneDayPriceChange': -0.001,
    'oneWeekPriceChange': 0.0015,
    'oneMonthPriceChange': -0.011,
    'lastTradePrice': 0.015,
    'bestBid': 0.013,
    'bestAsk': 0.014,
    'automaticallyActive': True,
    'clearBookOnStart': True,
    'manualActivation': False,
    'negRiskOther': False,
    'umaResolutionStatuses': '[]',
    'pendingDeployment': False,
    'deploying': False,
    'rfqEnabled': False,
    'holdingRewardsEnabled': False,
    'feesEnabled': False}],
  'tags': [{'id': '100196',
    'label': 'Fed Rates',
    'slug': 'fed-rates',
    'forceShow': True,
    'updatedAt': '2024-04-10T13:45:50.469564Z'},
   {'id': '107',
    'label': 'Business',
    'slug': 'business',
    'forceShow': False,
    'publishedAt': '2023-11-02 21:20:37.48+00',
    'createdAt': '2023-11-02T21:20:37.488Z',
    'updatedAt': '2024-07-05T21:07:24.910181Z'},
   {'id': '101588',
    'label': '2025 Predictions',
    'slug': '2025-predictions',
    'forceShow': False,
    'createdAt': '2024-12-30T20:11:13.144816Z',
    'updatedAt': '2024-12-30T20:19:11.195161Z'},
   {'id': '101800',
    'label': 'Economic Policy',
    'slug': 'economic-policy',
    'forceShow': False,
    'createdAt': '2025-02-06T18:05:50.554703Z'},
   {'id': '101550',
    'label': 'Jerome Powell',
    'slug': 'jerome-powell',
    'createdAt': '2024-12-18T23:06:40.410115Z'},
   {'id': '159',
    'label': 'Fed',
    'slug': 'fed',
    'forceShow': False,
    'publishedAt': '2023-11-02 21:27:18.98+00',
    'createdAt': '2023-11-02T21:27:18.986Z',
    'updatedAt': '2025-07-15T20:06:08.797075Z',
    'isCarousel': False}],
  'cyom': False,
  'showAllOutcomes': True,
  'showMarketImages': True,
  'enableNegRisk': False,
  'automaticallyActive': True,
  'negRiskAugmented': False,
  'pendingDeployment': False,
  'deploying': False},
 {'id': '16085',
  'ticker': 'how-many-fed-rate-cuts-in-2025',
  'slug': 'how-many-fed-rate-cuts-in-2025',
  'title': 'How many Fed rate cuts in 2025?',
  'description': 'This is a market group over how many Fed rate cuts will happen in 2025.',
  'resolutionSource': '',
  'startDate': '2024-12-29T22:50:43.348587Z',
  'creationDate': '2024-12-29T22:50:43.348584Z',
  'endDate': '2025-12-31T12:00:00Z',
  'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/how-many-fed-rate-cuts-in-2025-9qstZkSL1dn0.jpg',
  'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/how-many-fed-rate-cuts-in-2025-9qstZkSL1dn0.jpg',
  'active': True,
  'closed': False,
  'archived': False,
  'new': False,
  'featured': False,
  'restricted': True,
  'liquidity': 1117211.74063,
  'volume': 23361752.236576,
  'openInterest': 0,
  'createdAt': '2024-12-29T17:39:19.350409Z',
  'updatedAt': '2025-11-08T19:50:18.981832Z',
  'competitive': 0.9577626664112633,
  'volume24hr': 102254.47593399997,
  'volume1wk': 1627319.2250149997,
  'volume1mo': 5568365.170009999,
  'volume1yr': 23360504.630622018,
  'enableOrderBook': True,
  'liquidityClob': 1117211.74063,
  'negRisk': True,
  'negRiskMarketID': '0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a731367b6554be00',
  'commentCount': 69,
  'markets': [{'id': '516723',
    'question': 'Will no Fed rate cuts happen in 2025?',
    'conditionId': '0xebfda84c91d3dafde3f49bd132aadc9e762b88023021806e7345cd526fc7e1fa',
    'slug': 'will-no-fed-rate-cuts-happen-in-2025',
    'resolutionSource': '',
    'endDate': '2025-12-10T12:00:00Z',
    'startDate': '2024-12-29T22:44:16.86863Z',
    'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/how-many-fed-rate-cuts-in-2025-9qstZkSL1dn0.jpg',
    'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/how-many-fed-rate-cuts-in-2025-9qstZkSL1dn0.jpg',
    'description': 'The FED interest rates are defined in this market by the upper bound of the target federal funds range. The decisions on the target federal fund range are made by the Federal Open Market Committee (FOMC) meetings.\n\nThis market will resolve to “Yes” if the there no rate cuts by the Fed\'s December meeting (including the Dec meeting). Otherwise, this market will resolve to “No.”\n\nThis market may resolve to "Yes" immediately after the statement from the Fed\'s December 2025 meeting has been released if there has been no rate cuts by then.\n\nIf there is a rate cut at any time within 2025, before the statement following the December FOMC meeting is released, this market may immediately resolve to "No".\n\nThe resolution source for this market will be FOMC statements after meetings scheduled in 2025 according to the official calendar: https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm. The level and change of the target federal funds rate is also published at the official website of the Federal Reserve at https://www.federalreserve.gov/monetarypolicy/openmarket.htm.',
    'outcomes': '["Yes", "No"]',
    'outcomePrices': '["0", "1"]',
    'volume': '3257922.893311',
    'active': True,
    'closed': True,
    'marketMakerAddress': '',
    'createdAt': '2024-12-29T19:49:27.907976Z',
    'updatedAt': '2025-09-19T00:51:22.673698Z',
    'closedTime': '2025-09-17 21:39:36+00',
    'new': False,
    'featured': False,
    'submitted_by': '0x91430CaD2d3975766499717fA0D66A78D814E5c5',
    'archived': False,
    'resolvedBy': '0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d',
    'restricted': True,
    'groupItemTitle': '0',
    'groupItemThreshold': '0',
    'questionID': '0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a731367b6554be00',
    'umaEndDate': '2025-09-17T21:39:36Z',
    'enableOrderBook': True,
    'orderPriceMinTickSize': 0.001,
    'orderMinSize': 5,
    'umaResolutionStatus': 'resolved',
    'volumeNum': 3257922.893311,
    'endDateIso': '2025-12-10',
    'startDateIso': '2024-12-29',
    'hasReviewedDates': True,
    'volume1wk': 236059.86612599998,
    'volume1mo': 729035.9635269996,
    'volume1yr': 3257922.893311002,
    'clobTokenIds': '["18020161444416260195750543688224692006431301166904957549340226313298366177208", "22815929348267525865179400270560699202940891762662686118783091319501232508008"]',
    'umaBond': '500',
    'umaReward': '5',
    'volume1wkClob': 236059.86612599998,
    'volume1moClob': 729035.9635269996,
    'volume1yrClob': 3257922.893311002,
    'volumeClob': 3257922.893311,
    'acceptingOrders': False,
    'negRisk': True,
    'negRiskMarketID': '0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a731367b6554be00',
    'negRiskRequestID': '0x4dd53c9b0d616686cea42b92e8886696ea98740d1b249052e6d3b801de11ca77',
    'ready': False,
    'funded': False,
    'acceptingOrdersTimestamp': '2024-12-29T22:42:48Z',
    'cyom': False,
    'pagerDutyNotificationEnabled': False,
    'approved': True,
    'clobRewards': [{'id': '12269',
      'conditionId': '0xebfda84c91d3dafde3f49bd132aadc9e762b88023021806e7345cd526fc7e1fa',
      'assetAddress': '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174',
      'rewardsAmount': 0,
      'rewardsDailyRate': 5,
      'startDate': '2024-12-29',
      'endDate': '2500-12-31'}],
    'rewardsMinSize': 100,
    'rewardsMaxSpread': 3.5,
    'spread': 0.001,
    'automaticallyResolved': True,
    'oneDayPriceChange': -0.003,
    'oneWeekPriceChange': -0.0115,
    'oneMonthPriceChange': -0.0945,
    'lastTradePrice': 1,
    'bestAsk': 0.001,
    'automaticallyActive': True,
    'clearBookOnStart': True,
    'seriesColor': '',
    'manualActivation': False,
    'negRiskOther': False,
    'umaResolutionStatuses': '["proposed", "resolved"]',
    'pendingDeployment': False,
    'deploying': False,
    'rfqEnabled': False,
    'holdingRewardsEnabled': False,
    'feesEnabled': False},
   {'id': '516730',
    'question': 'Will 7 Fed rate cuts happen in 2025?',
    'conditionId': '0xf4d03ce9ce65ea06654f23e26dead828005511d65bb650cd5a9dc77891406d12',
    'slug': 'will-7-fed-rate-cuts-happen-in-2025',
    'resolutionSource': '',
    'endDate': '2025-12-10T12:00:00Z',
    'liquidity': '290616.75012',
    'startDate': '2024-12-29T22:49:01.543705Z',
    'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/how-many-fed-rate-cuts-in-2025-9qstZkSL1dn0.jpg',
    'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/how-many-fed-rate-cuts-in-2025-9qstZkSL1dn0.jpg',
    'description': 'The FED interest rates are defined in this market by the upper bound of the target federal funds range. The decisions on the target federal fund range are made by the Federal Open Market Committee (FOMC) meetings.\n\nThis market will resolve to “Yes” if the there are exactly 7 cuts of 25 basis points by the Fed\'s December meeting (including any cuts made during Dec meeting). Otherwise, this market will resolve to “No.”\n\nThis market may resolve to "Yes" immediately after the statement from the Fed\'s December 2025 meeting has been released if there has been exactly 7 rate cuts by then.\n\nFor example, if the FED cuts rates by 50 bps after a meeting, it would be considered 2 cuts (of 25 bps each). If there are 8 or more rate cuts at any point before this market\'s resolution date, this market will resolve to "No".\n\nNote that cuts between 1-24 bps (inclusive) will also be considered 1 rate cut.\n\nThe resolution source for this market will be FOMC statements after meetings scheduled in 2025 according to the official calendar: https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm. The level and change of the target federal funds rate is also published at the official website of the Federal Reserve at https://www.federalreserve.gov/monetarypolicy/openmarket.htm.',
    'outcomes': '["Yes", "No"]',
    'outcomePrices': '["0.0015", "0.9985"]',
    'volume': '2764386.95064',
    'active': True,
    'closed': False,
    'marketMakerAddress': '',
    'createdAt': '2024-12-29T20:35:34.291374Z',
    'updatedAt': '2025-11-08T19:53:13.072743Z',
    'new': False,
    'featured': False,
    'submitted_by': '0x91430CaD2d3975766499717fA0D66A78D814E5c5',
    'archived': False,
    'resolvedBy': '0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d',
    'restricted': True,
    'groupItemTitle': '7 (175 bps)',
    'groupItemThreshold': '7',
    'questionID': '0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a731367b6554be07',
    'enableOrderBook': True,
    'orderPriceMinTickSize': 0.001,
    'orderMinSize': 5,
    'volumeNum': 2764386.95064,
    'liquidityNum': 290616.75012,
    'endDateIso': '2025-12-10',
    'startDateIso': '2024-12-29',
    'hasReviewedDates': True,
    'volume24hr': 6246.6269999999995,
    'volume1wk': 340763.9163309999,
    'volume1mo': 1079674.4583289986,
    'volume1yr': 2763530.684640008,
    'clobTokenIds': '["106637218023173886895550072700357013102189022015797096007920322441434274793343", "79328870430805014620288089322067795525620481132773427804769291919755554601870"]',
    'umaBond': '500',
    'umaReward': '5',
    'volume24hrClob': 6246.6269999999995,
    'volume1wkClob': 340763.9163309999,
    'volume1moClob': 1079674.4583289986,
    'volume1yrClob': 2763530.684640008,
    'volumeClob': 2764386.95064,
    'liquidityClob': 290616.75012,
    'acceptingOrders': True,
    'negRisk': True,
    'negRiskMarketID': '0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a731367b6554be00',
    'negRiskRequestID': '0xb9c9f7d9d6ffc8464777f8e52c171b21abf668e1c4c5730e157aedbc58089b61',
    'ready': False,
    'funded': False,
    'acceptingOrdersTimestamp': '2024-12-29T22:47:51Z',
    'cyom': False,
    'competitive': 0.8009597099244316,
    'pagerDutyNotificationEnabled': False,
    'approved': True,
    'rewardsMinSize': 200,
    'rewardsMaxSpread': 3.5,
    'spread': 0.001,
    'oneMonthPriceChange': -0.001,
    'lastTradePrice': 0.001,
    'bestBid': 0.001,
    'bestAsk': 0.002,
    'automaticallyActive': True,
    'clearBookOnStart': True,
    'seriesColor': '',
    'showGmpSeries': False,
    'showGmpOutcome': False,
    'manualActivation': False,
    'negRiskOther': False,
    'umaResolutionStatuses': '[]',
    'pendingDeployment': False,
    'deploying': False,
    'rfqEnabled': False,
    'holdingRewardsEnabled': False,
    'feesEnabled': False},
   {'id': '516724',
    'question': 'Will 1 Fed rate cut happen in 2025?',
    'conditionId': '0x8e9b6942b4dac3117dadfacac2edb390b6d62d59c14152774bb5fcd983fc134e',
    'slug': 'will-1-fed-rate-cut-happen-in-2025',
    'resolutionSource': '',
    'endDate': '2025-12-10T12:00:00Z',
    'startDate': '2024-12-29T22:44:57.641884Z',
    'image': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/how-many-fed-rate-cuts-in-2025-9qstZkSL1dn0.jpg',
    'icon': 'https://polymarket-upload.s3.us-east-2.amazonaws.com/how-many-fed-rate-cuts-in-2025-9qstZkSL1dn0.jpg',
    'description': 'The FED interest rates are defined in this market by the upper bound of the target federal funds range. The decisions on the target federal fund range are made by the Federal Open Market Committee (FOMC) meetings.\n\nThis market will resolve to “Yes” if the there is exactly 1 cut of 25 basis points by the Fed\'s December meeting (including any cuts made during Dec meeting). Otherwise, this market will resolve to “No.”\n\nThis market may resolve to "Yes" immediately after the statement from the Fed\'s December 2025 meeting has been released if there has been exactly 1 rate cut by then.\n\nFor example, if the FED cuts rates by 50 bps after a meeting, it would be considered 2 cuts (of 25 bps each). If there are 2 or more rate cuts at any point before this market\'s resolution date, this market will resolve to "No".\n\nNote that cuts between 1-24 bps (inclusive) will also be considered 1 rate cut.\n\nThe resolution source for this market will be FOMC statements after meetings scheduled in 2025 according to the official calendar: https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm. The level and change of the target federal funds rate is also published at the official website of the Federal Reserve at https://www.federalreserve.gov/monetarypolicy/openmarket.htm.',
    'outcomes': '["Yes", "No"]',
    'outcomePrices': '["0", "1"]',
    'volume': '2906248.945921',
    'active': True,
    'closed': True,
    'marketMakerAddress': '',
    'createdAt': '2024-12-29T19:53:12.962104Z',
    'updatedAt': '2025-10-31T00:31:59.310897Z',
    'closedTime': '2025-10-29 21:18:07+00',
    'new': False,
    'featured': False,
    'submitted_by': '0x91430CaD2d3975766499717fA0D66A78D814E5c5',
    'archived': False,
    'resolvedBy': '0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d',
    'restricted': True,
    'groupItemTitle': '1 (25 bps)',
    'groupItemThreshold': '1',
    'questionID': '0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a731367b6554be01',
    'umaEndDate': '2025-10-29T21:18:07Z',
    'enableOrderBook': True,
    'orderPriceMinTickSize': 0.001,
    'orderMinSize': 5,
    'umaResolutionStatus': 'resolved',
    'volumeNum': 2906248.945921,
    'endDateIso': '2025-12-10',
    'startDateIso': '2024-12-29',
    'hasReviewedDates': True,
    'volume1wk': 303704.3263139999,
    'volume1mo': 705175.038868,
    'volume1yr': 2906248.9459210015,
    'clobTokenIds': '["15353185604353847122370324954202969073036867278400776447048296624042585335546", "26444182150998636640530251053223191773083977191941080891981240618283910212190"]',
    'umaBond': '500',
    'umaReward': '5',
    'volume1wkClob': 303704.3263139999,

In [55]:
# Create a pandas DataFrame from the Polymarket /events?closed=false response JSON.
# - Keeps ALL original market fields untouched (as columns)
# - Adds event fields with an 'event_' prefix (so you know the parent event)
# - Optionally parses JSON-in-strings and datetimes into helper columns

import pandas as pd
import json

def markets_df_from_events_response(response, parse_helpers=True):
    """
    response: the JSON returned by GET https://gamma-api.polymarket.com/events?closed=false
              (can be a list of events or a dict with an 'events' key)
    returns:  pandas.DataFrame with one row per market
    """
    # unwrap events list
    if isinstance(response, list):
        events = response
    elif isinstance(response, dict):
        events = response.get("events") or response.get("data") or [response]
        if not isinstance(events, list):
            events = [events]
    else:
        raise TypeError("Unsupported response type")

    rows = []
    for ev in events:
        markets = ev.get("markets") or ev.get("marketsData") or []
        # event metadata (prefix to avoid overwriting market keys)
        ev_meta = {f"event_{k}": v for k, v in ev.items() if k not in ("markets", "marketsData")}
        for m in markets:
            row = dict(m)       # keep market fields as-is
            row.update(ev_meta) # attach event info
            rows.append(row)

    df = pd.DataFrame(rows)

    if parse_helpers and not df.empty:
        # parse JSON-in-string arrays into helper columns (keep raw columns untouched)
        json_str_cols = ["outcomes", "shortOutcomes", "outcomePrices", "clobTokenIds", "umaResolutionStatuses"]
        for col in json_str_cols:
            if col in df.columns:
                def _parse_list(x):
                    if isinstance(x, str):
                        s = x.strip()
                        if s.startswith("[") and s.endswith("]"):
                            try:
                                return json.loads(s)
                            except Exception:
                                return None
                    return x
                df[col + "_list"] = df[col].apply(_parse_list)

        # parse datetimes into helper columns (keep raw strings)
        dt_cols = [
            "startDate","endDate","createdAt","updatedAt","acceptingOrdersTimestamp",
            "event_startDate","event_endDate","event_createdAt","event_updatedAt"
        ]
        for col in dt_cols:
            if col in df.columns:
                df[col + "_dt"] = pd.to_datetime(df[col], utc=True, errors="coerce")

        # coerce common numeric fields to numeric helper columns (raw kept)
        num_cols = [
            "volume","volumeNum","volumeClob","volume24hr","volume1wk","volume1mo","volume1yr",
            "volume24hrClob","volume1wkClob","volume1moClob","volume1yrClob",
            "liquidity","liquidityNum","liquidityClob",
            "bestBid","bestAsk","lastTradePrice","spread","orderPriceMinTickSize","orderMinSize",
            "competitive","rewardsMinSize","rewardsMaxSpread"
        ]
        for col in num_cols:
            if col in df.columns:
                df[col + "_num"] = pd.to_numeric(df[col], errors="coerce")

    return df

# --- usage ---
# import requests
# r = requests.get("https://gamma-api.polymarket.com/events?closed=false", timeout=15)
# response = r.json()
# df = markets_df_from_events_response(response)
# df.head()

In [56]:
df = markets_df_from_events_response(response)
df

,id,question,conditionId,slug,resolutionSource,endDate,liquidity,startDate,image,icon,description,outcomes,outcomePrices,volume,active,closed,marketMakerAddress,createdAt,updatedAt,new,featured,submitted_by,archived,resolvedBy,restricted,groupItemTitle,groupItemThreshold,questionID,enableOrderBook,orderPriceMinTickSize,orderMinSize,volumeNum,liquidityNum,endDateIso,startDateIso,hasReviewedDates,volume24hr,volume1wk,volume1mo,volume1yr,clobTokenIds,umaBond,umaReward,volume24hrClob,volume1wkClob,volume1moClob,volume1yrClob,volumeClob,liquidityClob,acceptingOrders,negRisk,ready,funded,acceptingOrdersTimestamp,cyom,competitive,pagerDutyNotificationEnabled,approved,rewardsMinSize,rewardsMaxSpread,spread,oneDayPriceChange,oneWeekPriceChange,oneMonthPriceChange,lastTradePrice,bestBid,bestAsk,automaticallyActive,clearBookOnStart,manualActivation,negRiskOther,umaResolutionStatuses,pendingDeployment,deploying,rfqEnabled,holdingRewardsEnabled,feesEnabled,event_id,event_ticker,event_slug,event_title,event_description,event_startDate,event_creationDate,event_endDate,event_image,event_icon,event_active,event_closed,event_archived,event_new,event_featured,event_restricted,event_liquidity,event_volume,event_openInterest,event_createdAt,event_updatedAt,event_competitive,event_volume24hr,event_volume1wk,event_volume1mo,event_volume1yr,event_enableOrderBook,event_liquidityClob,event_commentCount,event_tags,event_cyom,event_showAllOutcomes,event_showMarketImages,event_enableNegRisk,event_automaticallyActive,event_negRiskAugmented,event_pendingDeployment,event_deploying,closedTime,umaEndDate,umaResolutionStatus,negRiskMarketID,negRiskRequestID,clobRewards,automaticallyResolved,seriesColor,event_resolutionSource,event_negRisk,event_negRiskMarketID,event_gmpChartMode,showGmpSeries,showGmpOutcome,oneHourPriceChange,event_sortBy,event_series,event_seriesSlug,volume24hrAmm,volume1wkAmm,volume1moAmm,volume1yrAmm,volumeAmm,liquidityAmm,oneYearPriceChange,gameStartTime,event_startTime,customLiveness,deployingTimestamp,event_featuredOrder,event_eventDate,outcomes_list,outcomePrices_list,clobTokenIds_list,umaResolutionStatuses_list,startDate_dt,endDate_dt,createdAt_dt,updatedAt_dt,acceptingOrdersTimestamp_dt,event_startDate_dt,event_endDate_dt,event_createdAt_dt,event_updatedAt_dt,volume_num,volumeNum_num,volumeClob_num,volume24hr_num,volume1wk_num,volume1mo_num,volume1yr_num,volume24hrClob_num,volume1wkClob_num,volume1moClob_num,volume1yrClob_num,liquidity_num,liquidityNum_num,liquidityClob_num,bestBid_num,bestAsk_num,lastTradePrice_num,spread_num,orderPriceMinTickSize_num,orderMinSize_num,competitive_num,rewardsMinSize_num,rewardsMaxSpread_num
0,516706,Fed rate hike in 2025?,0x4319532e181605cb15b1bd677759a3bc7f7394b2fdf145195b700e...,fed-rate-hike-in-2025,,2025-12-10T12:00:00Z,60848.22599,2024-12-29T22:50:33.584839Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,This market will resolve to “Yes” if the upper bound of ...,"[""Yes"", ""No""]","[""0.0135"", ""0.9865""]",736030.554114,True,False,,2024-12-29T17:38:00.916304Z,2025-11-08T19:52:19.294139Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74,True,,0,0x8428884817cbc26422ec451101fcedfc5995907a8df6e5905bc29c...,True,0.001,5,7.360306e+05,60848.22599,2025-12-10,2024-12-29,True,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,"[""604871169844680209782472254744886767496010018298867559...",500,5,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,7.360306e+05,60848.22599,True,False,False,False,2024-12-29T22:49:15Z,False,0.808615,False,True,100,3.5,0.001,-0.001,0.0015,-0.0110,0.015,0.013,0.014,True,True,False,False,[],False,False,False,False,False,16084,fed-rate-hike-in-2025,fed-rate-hike-in-2025,Fed rate hike in 2025?,This market will resolve to “Yes” if the upper bound of ...,2024-12-29T22:50:44.013518Z,2024-12-29T22:50:44.013516Z,2025-12-10T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,True,False,False,False,False,True,6.084823e+04,7.360306e+05,0,2024-12-29T17:37:59.684632Z,2025-11-08T19:49:58.219481Z,0.808615,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,True,6.084823e+04,21,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,True,False,True,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.0135, 0.9865]",[6048711698446802097824722547448867674960100182988675596...,[],2024-12-29 22:50:33.584839+00:00,2025-12-10 12:00:00+00:00,2024-12-29 17:38:00.916304+00:00,2025-11-08 19:52:19.294139+00:00,2024-12-29 22:49:15+00:00,2024-12-29 22:50:44.013518+00:00,2025-12-10 12:00:00+00:00,2024-12-29 17:37:59.684632+00:00,2025-11-08 19:49:58.219481+00:00,7.360306e+05,7.360306e+05,7.360306e+05,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,60848.22599,60848.22599,60848.22599,0.013,0.014,0.015,0.001,0.001,5,0.808615,100,3.5
1,516723,Will no Fed rate cuts happen in 2025?,0xebfda84c91d3dafde3f49bd132aadc9e762b88023021806e7345cd...,will-no-fed-rate-cuts-happen-in-2025,,2025-12-10T12:00:00Z,NaN,2024-12-29T22:44:16.86863Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0"", ""1""]",3257922.893311,True,True,,2024-12-29T19:49:27.907976Z,2025-09-19T00:51:22.673698Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,0,0,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.001,5,3.257923e+06,NaN,2025-12-10,2024-12-29,True,NaN,2.360599e+05,7.290360e+05,3.257923e+06,"[""180201614444162601957505436882246920064313011669049575...",500,5,NaN,2.360599e+05,7.290360e+05,3.257923e+06,3.257923e+06,NaN,False,True,False,False,2024-12-29T22:42:48Z,False,NaN,False,True,100,3.5,0.001,-0.003,-0.0115,-0.0945,1.000,NaN,0.001,True,True,False,False,"[""proposed"", ""resolved""]",False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,2025-09-17 21:39:36+00,2025-09-17T21:39:36Z,resolved,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0x4dd53c9b0d616686cea42b92e8886696ea98740d1b249052e6d3b8...,"[{'id': '12269', 'conditionId': '0xebfda84c91d3dafde3f49...",True,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0, 1]",[1802016144441626019575054368822469200643130116690495754...,"[proposed, resolved]",2024-12-29 22:44:16.868630+00:00,2025-12-10 12:00:00+00:00,2024-12-29 19:49:27.907976+00:00,2025-09-19 00:51:22.673698+00:00,2024-12-29 22:42:48+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,3.257923e+06,3.257923e+06,3.257923e+06,NaN,2.360599e+05,7.290360e+05,3.257923e+06,NaN,2.360599e+05,7.290360e+05,3.257923e+06,NaN,NaN,NaN,NaN,0.001,1.000,0.001,0.001,5,NaN,100,3.5
2,516730,Will 7 Fed rate cuts happen in 2025?,0xf4d03ce9ce65ea06654f23e26dead828005511d65bb650cd5a9dc7...,will-7-fed-rate-cuts-happen-in-2025,,2025-12-10T12:00:00Z,290616.75012,2024-12-29T22:49:01.543705Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0.0015"", ""0.9985""]",2764386.95064,True,False,,2024-12-29T20:35:34.291374Z,2025-11-08T19:53:13.072743Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,7 (175 bps),7,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.001,5,2.764387e+06,290616.75012,2025-12-10,2024-12-29,True,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,"[""106637218023173886895550072700357013102189022015797096...",500,5,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,2.764387e+06,290616.75012,True,True,False,False,2024-12-29T22:47:51Z,False,0.800960,False,True,200,3.5,0.001,NaN,NaN,-0.0010,0.001,0.001,0.002,True,True,False,False,[],False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,NaN,NaN,NaN,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0xb9c9f7d9d6ffc8464777f8e52c171b21abf668e1c4c5730e157aed...,NaN,NaN,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.0015, 0.9985]",[1066372180231738868955500727003570131021890220157970960...,[],2024-12-29 22:49:01.543705+00:00,2025-12-10 12:00:00+00:00,2024-12-29 20:35:34.291374+00:00,2025-11-08 19:53:13.072743+00:00,2024-12-29 22:47:51+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,2.764387e+06,2.764387e+06,2.764387e+06,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,290616.75012,290616.75012,290616.75012,0.001,0.002,0.001,0.001,0.001,5,0.800960,200,3.5
3,516724,Will 1 Fed rate cut happen in 2025?,0x8e9b6942b4dac3117dadfacac2edb390b6d62d59c14152774bb5fc...,will-1-fed-rate-cut-happen-in-2025,,2025-12-10T12:00:00Z,NaN,2024-12-29T22:44:57.641884Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0"", ""1""]",2906248.945921,True,True,,2024-12-29T19:53:12.962104Z,2025-10-31T00:31:59.310897Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,1 (25 bps),1,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.001,5,2.906249e+06,NaN,2025-12-10,2024-12-29,True,NaN,3.037043e+05,7.051750e+05,2.906249e+06,"[""153531856043538471223703249542029690730368672784007764...",500,5,NaN,3.037043e+05,7.051750e+05,2.906249e+06,2.906249e+06,NaN,False,True,False,False,2024-12-29T22:43:48Z,False,NaN,False,True,200,3.5,0.001,-0.001,-0.0090,-0.0600,1.000,NaN,0.001,True,True,False,False,"[""proposed"", ""resolved""]",False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,2025-10-29 21:18:07+00,2025-10-29T21:18:07Z,resolved,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0xef6971601b767913c85fd9dd595ea3e73c561df29533e6eb8d9273...,NaN,True,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,False,False,-0.0005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0, 1]",[1535318560435384712237032495420296907303686727840077644...,"[proposed, resolved]",2024-12-29 22:44:57.641884+00:00,2025-12-10 12:00:00+00:00,2024-12-29 19:53:12.962104+00:00,2025-10-31 00:31:59.310897+00:00,2024-12-29 22:43:48+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,2.906249e+06,2.906249e+06,2.906249e+06,NaN,3.037043e+05,7.051750e+05,2.906249e+06,NaN,3.037043e+05,7.051750e+05,2.906249e+06,NaN,NaN,NaN,NaN,0.001,1.000,0.001,0.001,5,NaN,200,3.5
4,516725,Will 2 Fed rate cuts happen in 2025?,0x05af636e0989accb08334a74f69e5368e0aa28fe498fd16a3ca991...,will-2-fed-rate-cuts-happen-in-2025,,2025-12-10T12:00:00Z,106222.6918,2024-12-29T22:45:22.634712Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0.26"", ""0.74""]",2549051.093994,True,False,,2024-12-29T19:54:57.254583Z,2025-11-08T19:49:47.05871Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,2 (50 bps),2,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.010,5,2.549051e+06,106222.69180,2025-12-10,2024-12-29,True,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,"[""116618822484255790287301271222265880748441095175329062...",500,5,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,2.549051e+06,106222.69180,True,True,False,False,2024-12-29T22:44:14Z,False,0.945537,False,True,200,3.5,0.020,-0.005,-0.0500,0.0500,0.250,0.250,0.270,True,True,False,False,[],False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,NaN,NaN,NaN,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0x8b77dbf0e57a1c31eb3dbc187132706ec0cbc98a1f38083017a436...,"[{'id': '12267', 'conditionId': '0x05af636e0989accb08334...",NaN,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.26, 0.74]",[1166188224842557902873012712222658807484410951753290627...,[],2024-12-29 22:45:22.634712+00:00,2025-12-10 12:00:00+00:00,2024-12-29 19:54:57.254583+00:00,2025-11-08 19:49:47.058710+00:00,2024-12-29 22:44:14+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,2.549051e+06,2.549051e+06,2.549051e+06,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,106222.69180,106222.69180,106222.69180,0.250,0.270,0.250,0.020,0.010,5,0.945537,200,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,516717,Nuclear weapon detonation in 2025?,0x9fcb9901d142b5046467b4ea329508bdb19274eb1fd0fc833ee191...,nuclear-weapon-detonation-in-2025,,2025-12-31T12:00:00Z,66502.0345,2024-12-29T22:39:18.322Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/nuc...,https://polymarket-upload.s3.us-east-2.amazonaws.com/nuc...,"This market will resolve to ""Yes"" if a nuclear weapon is...","[""Yes"", ""No""]","[""0.055"", ""0.945""]",1780600.482019,True,False,,2024-12-29T18:46:41.126775Z,2025-11-08T19:47:33.204136Z,False,True,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74,True,,0,0x10092131269d990780a075751fda4f488a822a774435b986b0c4b4...,True,0.010,5,1.780600e+06,66502.03450,2025-12-31,2024-12-29,True,56517.816522,3.808655e+05,5.907178e+05,1.778334e+06,"[""849336686017746895150317394134151776066773443008368241...",500,5,56517.816522,3.808655e+05,5.907178e+05,1.778334e+06,1.780600e+06,66502.03450,True,False,False,False,2024-12-29T22:38:10Z,False,0.834707,False,True,200,3.5,0.010,0.010,NaN,NaN,0.060,0.050,0.060,True,True,False,False,[],False,False,False,False,False,16106,nuclear-weapon-detonation-in-2025,nuclear-weapon-detonation-in-2025,Nuclear weapon detonation in 2025?,"This market will resolve to ""Yes"" if a nuclear weapon is...",2024-12-29T22:40:14.244347Z,2024-12-29T22:40:14.244345Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/nuc...,https://polymarket-upload.s3.us-east-2.amazonaws.com/nuc...,True,False,False,False,True,True,6.650203e+04,1.780600e+06,0,2024-12-29T18:46:40.348933Z,2025-11-08T19:50:19.464695Z,0.834707,56517.816522,3.808655e+05,5.907178e+05,1.778334e+06,True,6.650203e+04,0,"[{'id': '101588', 'label': '2025 Predictions', 'slug': '...",False,True,True,False,True,False,False,False,NaN,NaN,NaN,NaN,NaN,"[{'id': '12273', 'conditionId': '0x9fcb9901d142b5046467b...",NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'id': '10593', 'ticker': 'nuclear-test', 'slug': 'nucl...",nuclear-test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,"[Yes, No]","[0.055, 0.945]",[8493366860177468951503173941341517760667734430083682413...,[],2024-12-29 22:39:18.322000+00:00,2025-12-31 12:00:00+00:00,2024-12-29 18:46:41.126775+00:00,2025-11-08 19:47:33.204136+00:00,2024-12-29 22:38:10+00:00,2024-12-29 22:40:14.244347+00:00,2025-12-31 12:00:00+00:00,2024-12-29 18:46:40.348933+00:00,2025-11-08 19:50:19.464695+00:00,1.780600e+06,1.780600e+06,1.780600e+06,56517.816522,3.808655e+05,5.907178e+05,1.778334e+06,56517.816522,3.808655e+05,5.907178e+05,1.778334e+06,66502.03450,66502.03450,66502.03450,0.050,0.060,0.060,0.010,0.010,5,0.834707,200,3.5

In [59]:
df_active = df[df['active'] == True]
df_active

,id,question,conditionId,slug,resolutionSource,endDate,liquidity,startDate,image,icon,description,outcomes,outcomePrices,volume,active,closed,marketMakerAddress,createdAt,updatedAt,new,featured,submitted_by,archived,resolvedBy,restricted,groupItemTitle,groupItemThreshold,questionID,enableOrderBook,orderPriceMinTickSize,orderMinSize,volumeNum,liquidityNum,endDateIso,startDateIso,hasReviewedDates,volume24hr,volume1wk,volume1mo,volume1yr,clobTokenIds,umaBond,umaReward,volume24hrClob,volume1wkClob,volume1moClob,volume1yrClob,volumeClob,liquidityClob,acceptingOrders,negRisk,ready,funded,acceptingOrdersTimestamp,cyom,competitive,pagerDutyNotificationEnabled,approved,rewardsMinSize,rewardsMaxSpread,spread,oneDayPriceChange,oneWeekPriceChange,oneMonthPriceChange,lastTradePrice,bestBid,bestAsk,automaticallyActive,clearBookOnStart,manualActivation,negRiskOther,umaResolutionStatuses,pendingDeployment,deploying,rfqEnabled,holdingRewardsEnabled,feesEnabled,event_id,event_ticker,event_slug,event_title,event_description,event_startDate,event_creationDate,event_endDate,event_image,event_icon,event_active,event_closed,event_archived,event_new,event_featured,event_restricted,event_liquidity,event_volume,event_openInterest,event_createdAt,event_updatedAt,event_competitive,event_volume24hr,event_volume1wk,event_volume1mo,event_volume1yr,event_enableOrderBook,event_liquidityClob,event_commentCount,event_tags,event_cyom,event_showAllOutcomes,event_showMarketImages,event_enableNegRisk,event_automaticallyActive,event_negRiskAugmented,event_pendingDeployment,event_deploying,closedTime,umaEndDate,umaResolutionStatus,negRiskMarketID,negRiskRequestID,clobRewards,automaticallyResolved,seriesColor,event_resolutionSource,event_negRisk,event_negRiskMarketID,event_gmpChartMode,showGmpSeries,showGmpOutcome,oneHourPriceChange,event_sortBy,event_series,event_seriesSlug,volume24hrAmm,volume1wkAmm,volume1moAmm,volume1yrAmm,volumeAmm,liquidityAmm,oneYearPriceChange,gameStartTime,event_startTime,customLiveness,deployingTimestamp,event_featuredOrder,event_eventDate,outcomes_list,outcomePrices_list,clobTokenIds_list,umaResolutionStatuses_list,startDate_dt,endDate_dt,createdAt_dt,updatedAt_dt,acceptingOrdersTimestamp_dt,event_startDate_dt,event_endDate_dt,event_createdAt_dt,event_updatedAt_dt,volume_num,volumeNum_num,volumeClob_num,volume24hr_num,volume1wk_num,volume1mo_num,volume1yr_num,volume24hrClob_num,volume1wkClob_num,volume1moClob_num,volume1yrClob_num,liquidity_num,liquidityNum_num,liquidityClob_num,bestBid_num,bestAsk_num,lastTradePrice_num,spread_num,orderPriceMinTickSize_num,orderMinSize_num,competitive_num,rewardsMinSize_num,rewardsMaxSpread_num
0,516706,Fed rate hike in 2025?,0x4319532e181605cb15b1bd677759a3bc7f7394b2fdf145195b700e...,fed-rate-hike-in-2025,,2025-12-10T12:00:00Z,60848.22599,2024-12-29T22:50:33.584839Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,This market will resolve to “Yes” if the upper bound of ...,"[""Yes"", ""No""]","[""0.0135"", ""0.9865""]",736030.554114,True,False,,2024-12-29T17:38:00.916304Z,2025-11-08T19:52:19.294139Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74,True,,0,0x8428884817cbc26422ec451101fcedfc5995907a8df6e5905bc29c...,True,0.001,5,7.360306e+05,60848.22599,2025-12-10,2024-12-29,True,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,"[""604871169844680209782472254744886767496010018298867559...",500,5,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,7.360306e+05,60848.22599,True,False,False,False,2024-12-29T22:49:15Z,False,0.808615,False,True,100,3.5,0.001,-0.001,0.0015,-0.0110,0.015,0.013,0.014,True,True,False,False,[],False,False,False,False,False,16084,fed-rate-hike-in-2025,fed-rate-hike-in-2025,Fed rate hike in 2025?,This market will resolve to “Yes” if the upper bound of ...,2024-12-29T22:50:44.013518Z,2024-12-29T22:50:44.013516Z,2025-12-10T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,True,False,False,False,False,True,6.084823e+04,7.360306e+05,0,2024-12-29T17:37:59.684632Z,2025-11-08T19:49:58.219481Z,0.808615,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,True,6.084823e+04,21,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,True,False,True,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.0135, 0.9865]",[6048711698446802097824722547448867674960100182988675596...,[],2024-12-29 22:50:33.584839+00:00,2025-12-10 12:00:00+00:00,2024-12-29 17:38:00.916304+00:00,2025-11-08 19:52:19.294139+00:00,2024-12-29 22:49:15+00:00,2024-12-29 22:50:44.013518+00:00,2025-12-10 12:00:00+00:00,2024-12-29 17:37:59.684632+00:00,2025-11-08 19:49:58.219481+00:00,7.360306e+05,7.360306e+05,7.360306e+05,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,60848.22599,60848.22599,60848.22599,0.013,0.014,0.015,0.001,0.001,5,0.808615,100,3.5
1,516723,Will no Fed rate cuts happen in 2025?,0xebfda84c91d3dafde3f49bd132aadc9e762b88023021806e7345cd...,will-no-fed-rate-cuts-happen-in-2025,,2025-12-10T12:00:00Z,NaN,2024-12-29T22:44:16.86863Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0"", ""1""]",3257922.893311,True,True,,2024-12-29T19:49:27.907976Z,2025-09-19T00:51:22.673698Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,0,0,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.001,5,3.257923e+06,NaN,2025-12-10,2024-12-29,True,NaN,2.360599e+05,7.290360e+05,3.257923e+06,"[""180201614444162601957505436882246920064313011669049575...",500,5,NaN,2.360599e+05,7.290360e+05,3.257923e+06,3.257923e+06,NaN,False,True,False,False,2024-12-29T22:42:48Z,False,NaN,False,True,100,3.5,0.001,-0.003,-0.0115,-0.0945,1.000,NaN,0.001,True,True,False,False,"[""proposed"", ""resolved""]",False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,2025-09-17 21:39:36+00,2025-09-17T21:39:36Z,resolved,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0x4dd53c9b0d616686cea42b92e8886696ea98740d1b249052e6d3b8...,"[{'id': '12269', 'conditionId': '0xebfda84c91d3dafde3f49...",True,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0, 1]",[1802016144441626019575054368822469200643130116690495754...,"[proposed, resolved]",2024-12-29 22:44:16.868630+00:00,2025-12-10 12:00:00+00:00,2024-12-29 19:49:27.907976+00:00,2025-09-19 00:51:22.673698+00:00,2024-12-29 22:42:48+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,3.257923e+06,3.257923e+06,3.257923e+06,NaN,2.360599e+05,7.290360e+05,3.257923e+06,NaN,2.360599e+05,7.290360e+05,3.257923e+06,NaN,NaN,NaN,NaN,0.001,1.000,0.001,0.001,5,NaN,100,3.5
2,516730,Will 7 Fed rate cuts happen in 2025?,0xf4d03ce9ce65ea06654f23e26dead828005511d65bb650cd5a9dc7...,will-7-fed-rate-cuts-happen-in-2025,,2025-12-10T12:00:00Z,290616.75012,2024-12-29T22:49:01.543705Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0.0015"", ""0.9985""]",2764386.95064,True,False,,2024-12-29T20:35:34.291374Z,2025-11-08T19:53:13.072743Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,7 (175 bps),7,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.001,5,2.764387e+06,290616.75012,2025-12-10,2024-12-29,True,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,"[""106637218023173886895550072700357013102189022015797096...",500,5,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,2.764387e+06,290616.75012,True,True,False,False,2024-12-29T22:47:51Z,False,0.800960,False,True,200,3.5,0.001,NaN,NaN,-0.0010,0.001,0.001,0.002,True,True,False,False,[],False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,NaN,NaN,NaN,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0xb9c9f7d9d6ffc8464777f8e52c171b21abf668e1c4c5730e157aed...,NaN,NaN,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.0015, 0.9985]",[1066372180231738868955500727003570131021890220157970960...,[],2024-12-29 22:49:01.543705+00:00,2025-12-10 12:00:00+00:00,2024-12-29 20:35:34.291374+00:00,2025-11-08 19:53:13.072743+00:00,2024-12-29 22:47:51+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,2.764387e+06,2.764387e+06,2.764387e+06,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,290616.75012,290616.75012,290616.75012,0.001,0.002,0.001,0.001,0.001,5,0.800960,200,3.5
3,516724,Will 1 Fed rate cut happen in 2025?,0x8e9b6942b4dac3117dadfacac2edb390b6d62d59c14152774bb5fc...,will-1-fed-rate-cut-happen-in-2025,,2025-12-10T12:00:00Z,NaN,2024-12-29T22:44:57.641884Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0"", ""1""]",2906248.945921,True,True,,2024-12-29T19:53:12.962104Z,2025-10-31T00:31:59.310897Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,1 (25 bps),1,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.001,5,2.906249e+06,NaN,2025-12-10,2024-12-29,True,NaN,3.037043e+05,7.051750e+05,2.906249e+06,"[""153531856043538471223703249542029690730368672784007764...",500,5,NaN,3.037043e+05,7.051750e+05,2.906249e+06,2.906249e+06,NaN,False,True,False,False,2024-12-29T22:43:48Z,False,NaN,False,True,200,3.5,0.001,-0.001,-0.0090,-0.0600,1.000,NaN,0.001,True,True,False,False,"[""proposed"", ""resolved""]",False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,2025-10-29 21:18:07+00,2025-10-29T21:18:07Z,resolved,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0xef6971601b767913c85fd9dd595ea3e73c561df29533e6eb8d9273...,NaN,True,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,False,False,-0.0005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0, 1]",[1535318560435384712237032495420296907303686727840077644...,"[proposed, resolved]",2024-12-29 22:44:57.641884+00:00,2025-12-10 12:00:00+00:00,2024-12-29 19:53:12.962104+00:00,2025-10-31 00:31:59.310897+00:00,2024-12-29 22:43:48+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,2.906249e+06,2.906249e+06,2.906249e+06,NaN,3.037043e+05,7.051750e+05,2.906249e+06,NaN,3.037043e+05,7.051750e+05,2.906249e+06,NaN,NaN,NaN,NaN,0.001,1.000,0.001,0.001,5,NaN,200,3.5
4,516725,Will 2 Fed rate cuts happen in 2025?,0x05af636e0989accb08334a74f69e5368e0aa28fe498fd16a3ca991...,will-2-fed-rate-cuts-happen-in-2025,,2025-12-10T12:00:00Z,106222.6918,2024-12-29T22:45:22.634712Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0.26"", ""0.74""]",2549051.093994,True,False,,2024-12-29T19:54:57.254583Z,2025-11-08T19:49:47.05871Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,2 (50 bps),2,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.010,5,2.549051e+06,106222.69180,2025-12-10,2024-12-29,True,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,"[""116618822484255790287301271222265880748441095175329062...",500,5,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,2.549051e+06,106222.69180,True,True,False,False,2024-12-29T22:44:14Z,False,0.945537,False,True,200,3.5,0.020,-0.005,-0.0500,0.0500,0.250,0.250,0.270,True,True,False,False,[],False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,NaN,NaN,NaN,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0x8b77dbf0e57a1c31eb3dbc187132706ec0cbc98a1f38083017a436...,"[{'id': '12267', 'conditionId': '0x05af636e0989accb08334...",NaN,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.26, 0.74]",[1166188224842557902873012712222658807484410951753290627...,[],2024-12-29 22:45:22.634712+00:00,2025-12-10 12:00:00+00:00,2024-12-29 19:54:57.254583+00:00,2025-11-08 19:49:47.058710+00:00,2024-12-29 22:44:14+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,2.549051e+06,2.549051e+06,2.549051e+06,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,106222.69180,106222.69180,106222.69180,0.250,0.270,0.250,0.020,0.010,5,0.945537,200,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
126,516717,Nuclear weapon detonation in 2025?,0x9fcb9901d142b5046467b4ea329508bdb19274eb1fd0fc833ee191...,nuclear-weapon-detonation-in-2025,,2025-12-31T12:00:00Z,66502.0345,2024-12-29T22:39:18.322Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/nuc...,https://polymarket-upload.s3.us-east-2.amazonaws.com/nuc...,"This market will resolve to ""Yes"" if a nuclear weapon is...","[""Yes"", ""No""]","[""0.055"", ""0.945""]",1780600.482019,True,False,,2024-12-29T18:46:41.126775Z,2025-11-08T19:47:33.204136Z,False,True,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74,True,,0,0x10092131269d990780a075751fda4f488a822a774435b986b0c4b4...,True,0.010,5,1.780600e+06,66502.03450,2025-12-31,2024-12-29,True,56517.816522,3.808655e+05,5.907178e+05,1.778334e+06,"[""849336686017746895150317394134151776066773443008368241...",500,5,56517.816522,3.808655e+05,5.907178e+05,1.778334e+06,1.780600e+06,66502.03450,True,False,False,False,2024-12-29T22:38:10Z,False,0.834707,False,True,200,3.5,0.010,0.010,NaN,NaN,0.060,0.050,0.060,True,True,False,False,[],False,False,False,False,False,16106,nuclear-weapon-detonation-in-2025,nuclear-weapon-detonation-in-2025,Nuclear weapon detonation in 2025?,"This market will resolve to ""Yes"" if a nuclear weapon is...",2024-12-29T22:40:14.244347Z,2024-12-29T22:40:14.244345Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/nuc...,https://polymarket-upload.s3.us-east-2.amazonaws.com/nuc...,True,False,False,False,True,True,6.650203e+04,1.780600e+06,0,2024-12-29T18:46:40.348933Z,2025-11-08T19:50:19.464695Z,0.834707,56517.816522,3.808655e+05,5.907178e+05,1.778334e+06,True,6.650203e+04,0,"[{'id': '101588', 'label': '2025 Predictions', 'slug': '...",False,True,True,False,True,False,False,False,NaN,NaN,NaN,NaN,NaN,"[{'id': '12273', 'conditionId': '0x9fcb9901d142b5046467b...",NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'id': '10593', 'ticker': 'nuclear-test', 'slug': 'nucl...",nuclear-test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,"[Yes, No]","[0.055, 0.945]",[8493366860177468951503173941341517760667734430083682413...,[],2024-12-29 22:39:18.322000+00:00,2025-12-31 12:00:00+00:00,2024-12-29 18:46:41.126775+00:00,2025-11-08 19:47:33.204136+00:00,2024-12-29 22:38:10+00:00,2024-12-29 22:40:14.244347+00:00,2025-12-31 12:00:00+00:00,2024-12-29 18:46:40.348933+00:00,2025-11-08 19:50:19.464695+00:00,1.780600e+06,1.780600e+06,1.780600e+06,56517.816522,3.808655e+05,5.907178e+05,1.778334e+06,56517.816522,3.808655e+05,5.907178e+05,1.778334e+06,66502.03450,66502.03450,66502.03450,0.050,0.060,0.060,0.010,0.010,5,0.834707,200,3.5

In [60]:
df_liquid = df_active[pd.to_numeric(df["liquidity"], errors="coerce").notna()]

/var/folders/b0/vnw_t5qn7zdccn_qsc7_4cs40000gn/T/ipykernel_73913/3623040812.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_liquid = df_active[pd.to_numeric(df["liquidity"], errors="coerce").notna()]

In [61]:

df_filtered = df_liquid.dropna(subset=["liquidity"])

In [62]:
df_filtered

,id,question,conditionId,slug,resolutionSource,endDate,liquidity,startDate,image,icon,description,outcomes,outcomePrices,volume,active,closed,marketMakerAddress,createdAt,updatedAt,new,featured,submitted_by,archived,resolvedBy,restricted,groupItemTitle,groupItemThreshold,questionID,enableOrderBook,orderPriceMinTickSize,orderMinSize,volumeNum,liquidityNum,endDateIso,startDateIso,hasReviewedDates,volume24hr,volume1wk,volume1mo,volume1yr,clobTokenIds,umaBond,umaReward,volume24hrClob,volume1wkClob,volume1moClob,volume1yrClob,volumeClob,liquidityClob,acceptingOrders,negRisk,ready,funded,acceptingOrdersTimestamp,cyom,competitive,pagerDutyNotificationEnabled,approved,rewardsMinSize,rewardsMaxSpread,spread,oneDayPriceChange,oneWeekPriceChange,oneMonthPriceChange,lastTradePrice,bestBid,bestAsk,automaticallyActive,clearBookOnStart,manualActivation,negRiskOther,umaResolutionStatuses,pendingDeployment,deploying,rfqEnabled,holdingRewardsEnabled,feesEnabled,event_id,event_ticker,event_slug,event_title,event_description,event_startDate,event_creationDate,event_endDate,event_image,event_icon,event_active,event_closed,event_archived,event_new,event_featured,event_restricted,event_liquidity,event_volume,event_openInterest,event_createdAt,event_updatedAt,event_competitive,event_volume24hr,event_volume1wk,event_volume1mo,event_volume1yr,event_enableOrderBook,event_liquidityClob,event_commentCount,event_tags,event_cyom,event_showAllOutcomes,event_showMarketImages,event_enableNegRisk,event_automaticallyActive,event_negRiskAugmented,event_pendingDeployment,event_deploying,closedTime,umaEndDate,umaResolutionStatus,negRiskMarketID,negRiskRequestID,clobRewards,automaticallyResolved,seriesColor,event_resolutionSource,event_negRisk,event_negRiskMarketID,event_gmpChartMode,showGmpSeries,showGmpOutcome,oneHourPriceChange,event_sortBy,event_series,event_seriesSlug,volume24hrAmm,volume1wkAmm,volume1moAmm,volume1yrAmm,volumeAmm,liquidityAmm,oneYearPriceChange,gameStartTime,event_startTime,customLiveness,deployingTimestamp,event_featuredOrder,event_eventDate,outcomes_list,outcomePrices_list,clobTokenIds_list,umaResolutionStatuses_list,startDate_dt,endDate_dt,createdAt_dt,updatedAt_dt,acceptingOrdersTimestamp_dt,event_startDate_dt,event_endDate_dt,event_createdAt_dt,event_updatedAt_dt,volume_num,volumeNum_num,volumeClob_num,volume24hr_num,volume1wk_num,volume1mo_num,volume1yr_num,volume24hrClob_num,volume1wkClob_num,volume1moClob_num,volume1yrClob_num,liquidity_num,liquidityNum_num,liquidityClob_num,bestBid_num,bestAsk_num,lastTradePrice_num,spread_num,orderPriceMinTickSize_num,orderMinSize_num,competitive_num,rewardsMinSize_num,rewardsMaxSpread_num
0,516706,Fed rate hike in 2025?,0x4319532e181605cb15b1bd677759a3bc7f7394b2fdf145195b700e...,fed-rate-hike-in-2025,,2025-12-10T12:00:00Z,60848.22599,2024-12-29T22:50:33.584839Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,This market will resolve to “Yes” if the upper bound of ...,"[""Yes"", ""No""]","[""0.0135"", ""0.9865""]",736030.554114,True,False,,2024-12-29T17:38:00.916304Z,2025-11-08T19:52:19.294139Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74,True,,0,0x8428884817cbc26422ec451101fcedfc5995907a8df6e5905bc29c...,True,0.001,5,7.360306e+05,60848.22599,2025-12-10,2024-12-29,True,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,"[""604871169844680209782472254744886767496010018298867559...",500,5,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,7.360306e+05,60848.22599,True,False,False,False,2024-12-29T22:49:15Z,False,0.808615,False,True,100,3.5,0.001,-0.0010,0.0015,-0.0110,0.015,0.013,0.014,True,True,False,False,[],False,False,False,False,False,16084,fed-rate-hike-in-2025,fed-rate-hike-in-2025,Fed rate hike in 2025?,This market will resolve to “Yes” if the upper bound of ...,2024-12-29T22:50:44.013518Z,2024-12-29T22:50:44.013516Z,2025-12-10T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,True,False,False,False,False,True,6.084823e+04,7.360306e+05,0,2024-12-29T17:37:59.684632Z,2025-11-08T19:49:58.219481Z,0.808615,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,True,6.084823e+04,21,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,True,False,True,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.0135, 0.9865]",[6048711698446802097824722547448867674960100182988675596...,[],2024-12-29 22:50:33.584839+00:00,2025-12-10 12:00:00+00:00,2024-12-29 17:38:00.916304+00:00,2025-11-08 19:52:19.294139+00:00,2024-12-29 22:49:15+00:00,2024-12-29 22:50:44.013518+00:00,2025-12-10 12:00:00+00:00,2024-12-29 17:37:59.684632+00:00,2025-11-08 19:49:58.219481+00:00,7.360306e+05,7.360306e+05,7.360306e+05,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,60848.22599,60848.22599,60848.22599,0.013,0.014,0.015,0.001,0.001,5,0.808615,100,3.5
2,516730,Will 7 Fed rate cuts happen in 2025?,0xf4d03ce9ce65ea06654f23e26dead828005511d65bb650cd5a9dc7...,will-7-fed-rate-cuts-happen-in-2025,,2025-12-10T12:00:00Z,290616.75012,2024-12-29T22:49:01.543705Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0.0015"", ""0.9985""]",2764386.95064,True,False,,2024-12-29T20:35:34.291374Z,2025-11-08T19:53:13.072743Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,7 (175 bps),7,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.001,5,2.764387e+06,290616.75012,2025-12-10,2024-12-29,True,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,"[""106637218023173886895550072700357013102189022015797096...",500,5,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,2.764387e+06,290616.75012,True,True,False,False,2024-12-29T22:47:51Z,False,0.800960,False,True,200,3.5,0.001,NaN,NaN,-0.0010,0.001,0.001,0.002,True,True,False,False,[],False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,NaN,NaN,NaN,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0xb9c9f7d9d6ffc8464777f8e52c171b21abf668e1c4c5730e157aed...,NaN,NaN,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.0015, 0.9985]",[1066372180231738868955500727003570131021890220157970960...,[],2024-12-29 22:49:01.543705+00:00,2025-12-10 12:00:00+00:00,2024-12-29 20:35:34.291374+00:00,2025-11-08 19:53:13.072743+00:00,2024-12-29 22:47:51+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,2.764387e+06,2.764387e+06,2.764387e+06,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,6246.627000,3.407639e+05,1.079674e+06,2.763531e+06,290616.75012,290616.75012,290616.75012,0.001,0.002,0.001,0.001,0.001,5,0.800960,200,3.5
4,516725,Will 2 Fed rate cuts happen in 2025?,0x05af636e0989accb08334a74f69e5368e0aa28fe498fd16a3ca991...,will-2-fed-rate-cuts-happen-in-2025,,2025-12-10T12:00:00Z,106222.6918,2024-12-29T22:45:22.634712Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0.26"", ""0.74""]",2549051.093994,True,False,,2024-12-29T19:54:57.254583Z,2025-11-08T19:49:47.05871Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,2 (50 bps),2,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.010,5,2.549051e+06,106222.69180,2025-12-10,2024-12-29,True,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,"[""116618822484255790287301271222265880748441095175329062...",500,5,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,2.549051e+06,106222.69180,True,True,False,False,2024-12-29T22:44:14Z,False,0.945537,False,True,200,3.5,0.020,-0.0050,-0.0500,0.0500,0.250,0.250,0.270,True,True,False,False,[],False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,NaN,NaN,NaN,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0x8b77dbf0e57a1c31eb3dbc187132706ec0cbc98a1f38083017a436...,"[{'id': '12267', 'conditionId': '0x05af636e0989accb08334...",NaN,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.26, 0.74]",[1166188224842557902873012712222658807484410951753290627...,[],2024-12-29 22:45:22.634712+00:00,2025-12-10 12:00:00+00:00,2024-12-29 19:54:57.254583+00:00,2025-11-08 19:49:47.058710+00:00,2024-12-29 22:44:14+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,2.549051e+06,2.549051e+06,2.549051e+06,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,62249.994874,2.046383e+05,6.557664e+05,2.548973e+06,106222.69180,106222.69180,106222.69180,0.250,0.270,0.250,0.020,0.010,5,0.945537,200,3.5
5,516731,Will 6 Fed rate cuts happen in 2025?,0x37100ed3560699c48d90a027e65da10a04e395785b598289163e3b...,will-6-fed-rate-cuts-happen-in-2025,,2025-12-10T12:00:00Z,267615.64147,2024-12-29T22:48:27.776106Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0.0015"", ""0.9985""]",2312487.813532,True,False,,2024-12-29T20:36:57.617602Z,2025-11-08T19:48:52.122875Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,6 (150 bps),6,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.001,5,2.312488e+06,267615.64147,2025-12-10,2024-12-29,True,3534.176500,1.121724e+05,6.309097e+05,2.312488e+06,"[""354286285899907471814569216108142066324050287171827604...",500,5,3534.176500,1.121724e+05,6.309097e+05,2.312488e+06,2.312488e+06,267615.64147,True,True,False,False,2024-12-29T22:47:17Z,False,0.800960,False,True,200,3.5,0.001,-0.0005,-0.0005,-0.0025,0.002,0.001,0.002,True,True,False,False,[],False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,NaN,NaN,NaN,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0x033b2dbd0328eea8a2a302be05efbc501aaf3312be1bec02404fbb...,NaN,NaN,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.0015, 0.9985]",[3542862858999074718145692161081420663240502871718276041...,[],2024-12-29 22:48:27.776106+00:00,2025-12-10 12:00:00+00:00,2024-12-29 20:36:57.617602+00:00,2025-11-08 19:48:52.122875+00:00,2024-12-29 22:47:17+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,2.312488e+06,2.312488e+06,2.312488e+06,3534.176500,1.121724e+05,6.309097e+05,2.312488e+06,3534.176500,1.121724e+05,6.309097e+05,2.312488e+06,267615.64147,267615.64147,267615.64147,0.001,0.002,0.002,0.001,0.001,5,0.800960,200,3.5
6,516726,Will 3 Fed rate cuts happen in 2025?,0x6df2f2ca434b5bacaef33d6b24edf42845199f4f794e66580de2d2...,will-3-fed-rate-cuts-happen-in-2025,,2025-12-10T12:00:00Z,47767.9981,2024-12-29T22:45:47.064873Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,The FED interest rates are defined in this market by the...,"[""Yes"", ""No""]","[""0.71"", ""0.29""]",2694377.692387,True,False,,2024-12-29T19:57:11.618587Z,2025-11-08T19:51:20.877591Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,3 (75 bps),3,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,True,0.010,5,2.694378e+06,47767.99810,2025-12-10,2024-12-29,True,20197.348546,1.339766e+05,5.674491e+05,2.694260e+06,"[""176017704422395632890822751811387499514228994428509163...",500,5,20197.348546,1.339766e+05,5.674491e+05,2.694260e+06,2.694378e+06,47767.99810,True,True,False,False,2024-12-29T22:44:34Z,False,0.957763,False,True,200,3.5,0.020,-0.0350,0.0650,0.0150,0.720,0.700,0.720,True,True,False,False,[],False,False,False,False,False,16085,how-many-fed-rate-cuts-in-2025,how-many-fed-rate-cuts-in-2025,How many Fed rate cuts in 2025?,This is a market group over how many Fed rate cuts will ...,2024-12-29T22:50:43.348587Z,2024-12-29T22:50:43.348584Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,1.117212e+06,2.336175e+07,0,2024-12-29T17:39:19.350409Z,2025-11-08T19:50:18.981832Z,0.957763,102254.475934,1.627319e+06,5.568365e+06,2.336050e+07,True,1.117212e+06,69,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,False,True,True,False,False,False,NaN,NaN,NaN,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,0x9cf39e79b6cd47e9fabcafcef10d0f49528ca3328caf091ff3b696...,"[{'id': '12266', 'conditionId': '0x6df2f2ca434b5bacaef33...",NaN,,,True,0x1bdcc22f99efd4a0af525806c64f7e6ee0a1640517b1d0a4a73136...,default,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.71, 0.29]",[1760177044223956328908227518113874995142289944285091633...,[],2024-12-29 22:45:47.064873+00:00,2025-12-10 12:00:00+00:00,2024-12-29 19:57:11.618587+00:00,2025-11-08 19:51:20.877591+00:00,2024-12-29 22:44:34+00:00,2024-12-29 22:50:43.348587+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:39:19.350409+00:00,2025-11-08 19:50:18.981832+00:00,2.694378e+06,2.694378e+06,2.694378e+06,20197.348546,1.339766e+05,5.674491e+05,2.694260e+06,20197.348546,1.339766e+05,5.674491e+05,2.694260e+06,47767.99810,47767.99810,47767.99810,0.700,0.720,0.720,0.020,0.010,5,0.957763,200,3.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,516716,Khamenei out as Supreme Leader of Iran in 2025?,0x1b6f76e5b8587ee896c35847e12d11e75290a8c3934c5952e8a9d6...,khamenei-out-as-supreme-leader-of-iran-in-2025,,2025-12-31T12:00:00Z,163258.5643,2024-12-29T22:39:48.361Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/kha...,https://polymarket-upload.s3.us-east-2.amazonaws.com/kha...,"This market will resolve to ""Yes"" if Iran's Supreme lead...","[""Yes"", ""No""]","[""0.065"", ""0.935""]",8640448.644141,True,False,,2024-12-29T18:46:01.774765Z,2025-11-08T19:52:07.460855Z,False,True,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74,True,,0,0x6927986b332a73045cb4fd63cf7eb1abfed158380d7a0d84c1e3ba...,True,0.010,5,8.640449e+06,163258.56430,2025-12-31,2024-12-29,True,3553.491884,6.005384e+05,1.656410e+06,8.640007e+06,"[""755057288182370761473187965360668123621523586063071540...",500,5,3553.491884,6.005384e+05,1.656410e+06,8.640007e+06,8.640449e+06,163258.56430,True,False,False,False,2024-12-29T22:38:40Z,False,0.840884,False,True,200,3.5,0.010,NaN,-0.0300,-0.1000,0.060,0.060,0.070,True,True,False,False,[],False,False,False,False,False,16105,khamenei-out-as-supreme-leader-of-iran-in-2025,khamenei-out-as-supreme-leader-of-iran-in-2025,Khamenei out as Supreme Leader of Iran in 2025?,"This market will resolve to ""Yes"" if Iran's Supreme lead...",2024-12-29T22:40:14.246543Z,2024-12-29T22:40:14.246542Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/kha...,https://polymarket-upload.s3.us-east-2.amazonaws.com/kha...,True,False,False,False,False,True,1.644178e+05,8.640449e+06,0,2024-12-29T18:46:00.835954Z,2025-11-08T19:50:14.912334Z,0.840884,3553.491884,6.005384e+05,1.656410e+06,8.640007e+06,True,1.644178e+05,1707,"[{'id': '101588', 'label': '2025 Predictions', 'slug': '...",False,True,True,False,True,False,False,False,NaN,NaN,NaN,NaN,NaN,"[{'id': '12274', 'conditionId': '0x1b6f76e5b8587ee896c35...",NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'id': '10126', 'ticker': 'khamenei-out', 'slug': 'kham...",khamenei-out,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.065, 0.935]",[7550572881823707614731879653606681236215235860630715408...,[],2024-12-29 22:39:48.361000+00:00,2025-12-31 12:00:00+00:00,2024-12-29 18:46:01.774765+00:00,2025-11-08 19:52:07.460855+00:00,2024-12-29 22:38:40+00:00,2024-12-29 22:40:14.246543+00:00,2025-12-31 12:00:00+00:00,2024-12-29 18:46:00.835954+00:00,2025-11-08 19:50:14.912334+00:00,8.640449e+06,8.640449e+06,8.640449e+06,3553.491884,6.005384e+05,1.656410e+06,8.640007e+06,3553.491884,6.005384e+05,1.656410e+06,8.640007e+06,163258.56430,163258.56430,163258.56430,0.060,0.070,0.060,0.010,0.010,5,0.840884,200,3.5

In [70]:
df = df_filtered

In [72]:
df_sample = df.sample(n=10, random_state=42)

In [73]:
df_sample

,id,question,conditionId,slug,resolutionSource,endDate,liquidity,startDate,image,icon,description,outcomes,outcomePrices,volume,active,closed,marketMakerAddress,createdAt,updatedAt,new,featured,submitted_by,archived,resolvedBy,restricted,groupItemTitle,groupItemThreshold,questionID,enableOrderBook,orderPriceMinTickSize,orderMinSize,volumeNum,liquidityNum,endDateIso,startDateIso,hasReviewedDates,volume24hr,volume1wk,volume1mo,volume1yr,clobTokenIds,umaBond,umaReward,volume24hrClob,volume1wkClob,volume1moClob,volume1yrClob,volumeClob,liquidityClob,acceptingOrders,negRisk,ready,funded,acceptingOrdersTimestamp,cyom,competitive,pagerDutyNotificationEnabled,approved,rewardsMinSize,rewardsMaxSpread,spread,oneDayPriceChange,oneWeekPriceChange,oneMonthPriceChange,lastTradePrice,bestBid,bestAsk,automaticallyActive,clearBookOnStart,manualActivation,negRiskOther,umaResolutionStatuses,pendingDeployment,deploying,rfqEnabled,holdingRewardsEnabled,feesEnabled,event_id,event_ticker,event_slug,event_title,event_description,event_startDate,event_creationDate,event_endDate,event_image,event_icon,event_active,event_closed,event_archived,event_new,event_featured,event_restricted,event_liquidity,event_volume,event_openInterest,event_createdAt,event_updatedAt,event_competitive,event_volume24hr,event_volume1wk,event_volume1mo,event_volume1yr,event_enableOrderBook,event_liquidityClob,event_commentCount,event_tags,event_cyom,event_showAllOutcomes,event_showMarketImages,event_enableNegRisk,event_automaticallyActive,event_negRiskAugmented,event_pendingDeployment,event_deploying,closedTime,umaEndDate,umaResolutionStatus,negRiskMarketID,negRiskRequestID,clobRewards,automaticallyResolved,seriesColor,event_resolutionSource,event_negRisk,event_negRiskMarketID,event_gmpChartMode,showGmpSeries,showGmpOutcome,oneHourPriceChange,event_sortBy,event_series,event_seriesSlug,volume24hrAmm,volume1wkAmm,volume1moAmm,volume1yrAmm,volumeAmm,liquidityAmm,oneYearPriceChange,gameStartTime,event_startTime,customLiveness,deployingTimestamp,event_featuredOrder,event_eventDate,outcomes_list,outcomePrices_list,clobTokenIds_list,umaResolutionStatuses_list,startDate_dt,endDate_dt,createdAt_dt,updatedAt_dt,acceptingOrdersTimestamp_dt,event_startDate_dt,event_endDate_dt,event_createdAt_dt,event_updatedAt_dt,volume_num,volumeNum_num,volumeClob_num,volume24hr_num,volume1wk_num,volume1mo_num,volume1yr_num,volume24hrClob_num,volume1wkClob_num,volume1moClob_num,volume1yrClob_num,liquidity_num,liquidityNum_num,liquidityClob_num,bestBid_num,bestAsk_num,lastTradePrice_num,spread_num,orderPriceMinTickSize_num,orderMinSize_num,competitive_num,rewardsMinSize_num,rewardsMaxSpread_num
119,516811,Will SpaceX have 200 or more launches in 2025?,0xc4e2af103f1f6e153cb07f9977b3cbdb5f04bb856a69036bbe8bd3...,will-spacex-have-200-or-more-launches-in-2025,https://www.faa.gov/data_research/commercial_space_data,2025-12-31T12:00:00Z,10590.2953,2024-12-30T15:45:04.881Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,"This market will resolve to ""Yes"" if SpaceX has 200 or m...","[""Yes"", ""No""]","[""0.034"", ""0.966""]",53998.851793,True,False,,2024-12-30T09:59:57.09901Z,2025-11-08T19:51:26.225403Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,200 or more,6,0x2e006ec2cba16a9569c684f3c1d6034d733d6db47639320ecfb2c8...,True,0.001,5,5.399885e+04,10590.29530,2025-12-31,2024-12-30,True,62.701242,3.651883e+02,2.465012e+04,5.399885e+04,"[""380635031837051225328721248613354823043024287055111031...",500,5,62.701242,3.651883e+02,2.465012e+04,5.399885e+04,5.399885e+04,10590.29530,True,True,False,False,2024-12-30T15:43:54Z,False,0.821587,False,True,50,3.5,0.002,-0.0005,-0.0030,0.0015,0.033,0.033,0.035,True,True,False,False,[],False,False,False,False,False,16102,how-many-spacex-launches-in-2025,how-many-spacex-launches-in-2025,How many SpaceX launches in 2025?,This is a market on predicting the total number of Space...,2024-12-30T15:45:51.508087Z,2024-12-30T15:45:51.508082Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,https://polymarket-upload.s3.us-east-2.amazonaws.com/how...,True,False,False,False,False,True,2.742521e+04,1.899876e+05,0,2024-12-29T18:40:07.980607Z,2025-11-08T19:50:14.732788Z,0.853079,1.259172e+03,1.206384e+04,4.842768e+04,1.896276e+05,True,2.742521e+04,11,"[{'id': '101588', 'label': '2025 Predictions', 'slug': '...",False,True,False,True,True,False,False,False,NaN,NaN,NaN,0x2e006ec2cba16a9569c684f3c1d6034d733d6db47639320ecfb2c8...,0x904489bdba7eaa1772d56d813740addced27faeed8f53d26f02e19...,"[{'id': '12275', 'conditionId': '0xc4e2af103f1f6e153cb07...",NaN,,,True,0x2e006ec2cba16a9569c684f3c1d6034d733d6db47639320ecfb2c8...,default,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.034, 0.966]",[3806350318370512253287212486133548230430242870551110318...,[],2024-12-30 15:45:04.881000+00:00,2025-12-31 12:00:00+00:00,2024-12-30 09:59:57.099010+00:00,2025-11-08 19:51:26.225403+00:00,2024-12-30 15:43:54+00:00,2024-12-30 15:45:51.508087+00:00,2025-12-31 12:00:00+00:00,2024-12-29 18:40:07.980607+00:00,2025-11-08 19:50:14.732788+00:00,5.399885e+04,5.399885e+04,5.399885e+04,62.701242,3.651883e+02,2.465012e+04,5.399885e+04,62.701242,3.651883e+02,2.465012e+04,5.399885e+04,10590.29530,10590.29530,10590.29530,0.033,0.035,0.033,0.002,0.001,5,0.821587,50,3.5
0,516706,Fed rate hike in 2025?,0x4319532e181605cb15b1bd677759a3bc7f7394b2fdf145195b700e...,fed-rate-hike-in-2025,,2025-12-10T12:00:00Z,60848.22599,2024-12-29T22:50:33.584839Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,This market will resolve to “Yes” if the upper bound of ...,"[""Yes"", ""No""]","[""0.0135"", ""0.9865""]",736030.554114,True,False,,2024-12-29T17:38:00.916304Z,2025-11-08T19:52:19.294139Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74,True,,0,0x8428884817cbc26422ec451101fcedfc5995907a8df6e5905bc29c...,True,0.001,5,7.360306e+05,60848.22599,2025-12-10,2024-12-29,True,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,"[""604871169844680209782472254744886767496010018298867559...",500,5,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,7.360306e+05,60848.22599,True,False,False,False,2024-12-29T22:49:15Z,False,0.808615,False,True,100,3.5,0.001,-0.0010,0.0015,-0.0110,0.015,0.013,0.014,True,True,False,False,[],False,False,False,False,False,16084,fed-rate-hike-in-2025,fed-rate-hike-in-2025,Fed rate hike in 2025?,This market will resolve to “Yes” if the upper bound of ...,2024-12-29T22:50:44.013518Z,2024-12-29T22:50:44.013516Z,2025-12-10T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,True,False,False,False,False,True,6.084823e+04,7.360306e+05,0,2024-12-29T17:37:59.684632Z,2025-11-08T19:49:58.219481Z,0.808615,6.078040e+03,6.098663e+04,1.851567e+05,7.360106e+05,True,6.084823e+04,21,"[{'id': '100196', 'label': 'Fed Rates', 'slug': 'fed-rat...",False,True,True,False,True,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.0135, 0.9865]",[6048711698446802097824722547448867674960100182988675596...,[],2024-12-29 22:50:33.584839+00:00,2025-12-10 12:00:00+00:00,2024-12-29 17:38:00.916304+00:00,2025-11-08 19:52:19.294139+00:00,2024-12-29 22:49:15+00:00,2024-12-29 22:50:44.013518+00:00,2025-12-10 12:00:00+00:00,2024-12-29 17:37:59.684632+00:00,2025-11-08 19:49:58.219481+00:00,7.360306e+05,7.360306e+05,7.360306e+05,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,6078.040000,6.098663e+04,1.851567e+05,7.360106e+05,60848.22599,60848.22599,60848.22599,0.013,0.014,0.015,0.001,0.001,5,0.808615,100,3.5
103,517019,Will How to Train Your Dragon be the top grossing movie ...,0x22fa7126aad142e3e7cd7dc6ae6669b86e28ff8ae6f07a57e1a054...,will-how-to-train-your-dragon-be-the-top-grossing-movie-...,,2025-12-31T12:00:00Z,528014.99402,2025-01-02T18:50:19.06847Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,https://polymarket-upload.s3.us-east-2.amazonaws.com/wil...,"This market will resolve to ""Yes"" if the ""Gross"" column ...","[""Yes"", ""No""]","[""0.0025"", ""0.9975""]",10107103.776104,True,False,,2025-01-01T12:51:30.849417Z,2025-11-08T19:51:41.379504Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x2F5e3684cb1F318ec51b00Edba38d79Ac2c0aA9d,True,How to Train Your Dragon,8,0x91eb615013098c0480e1ade0bf538d2c08312b03f76e19da7f5a0d...,True,0.001,5,1.010710e+07,528014.99402,2025-12-31,2025-01-02,True,227064.317000,1.859067e+06,5.341515e+06,1.010095e+07,"[""306464099792224951790106406053916017635952777261805761...",500,5,227064.317000,1.859067e+06,5.341515e+06,1.010095e+07,1.010710e+07,528014.99402,True,True,False,False,2025-01-02T18:49:04Z,False,0.801599,False,True,50,3.5,0.001,NaN,NaN,-0.0020,0.002,0.002,0.003,True,True,False,False,[],False,False,False,False,False,16100,highest-grossing-movie-in-2025,highest-grossing-movie-in-2025,Highest grossing movie in 2025?,This is a market on which movie will have the highest bo...,2025-01-02T18:53:07.440776Z,2025-01-02T18:53:07.440771Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/hig...,https://polymarket-upload.s3.us-east-2.amazonaws.com/hig...,True,False,False,False,False,True,3.261406e+06,6.403492e+07,0,2024-12-29T18:17:09.051969Z,2025-11-08T19:50:09.952588Z,0.997506,1.065504e+06,7.079667e+06,2.820425e+07,6.392310e+07,True,3.261406e+06,843,"[{'id': '51', 'label': 'box office', 'slug': 'box-office...",False,True,True,True,True,True,False,False,NaN,NaN,NaN,0x91eb615013098c0480e1ade0bf538d2c08312b03f76e19da7f5a0d...,0xb2ccc202bf72797d321ee3bb21177b595a1f5d35b39f58cf3a127f...,NaN,NaN,,,True,0x91eb615013098c0480e1ade0bf538d2c08312b03f76e19da7f5a0d...,default,False,False,NaN,price,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.0025, 0.9975]",[3064640997922249517901064060539160176359527772618057614...,[],2025-01-02 18:50:19.068470+00:00,2025-12-31 12:00:00+00:00,2025-01-01 12:51:30.849417+00:00,2025-11-08 19:51:41.379504+00:00,2025-01-02 18:49:04+00:00,2025-01-02 18:53:07.440776+00:00,2025-12-31 12:00:00+00:00,2024-12-29 18:17:09.051969+00:00,2025-11-08 19:50:09.952588+00:00,1.010710e+07,1.010710e+07,1.010710e+07,227064.317000,1.859067e+06,5.341515e+06,1.010095e+07,227064.317000,1.859067e+06,5.341515e+06,1.010095e+07,528014.99402,528014.99402,528014.99402,0.002,0.003,0.002,0.001,0.001,5,0.801599,50,3.5
35,516711,Fed emergency rate cut in 2025?,0xcddb4f52babca280f8e5fc4b9146f2520f0bfb88e134ff9ac8d52e...,fed-emergency-rate-cut-in-2025,,2025-12-31T12:00:00Z,52152.70195,2024-12-29T22:41:48.240383Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/fed...,https://polymarket-upload.s3.us-east-2.amazonaws.com/fed...,"This market will resolve to ""Yes"" if the Federal Open Ma...","[""Yes"", ""No""]","[""0.03"", ""0.97""]",1169100.906494,True,False,,2024-12-29T18:06:53.973587Z,2025-11-08T19:48:40.018498Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74,True,,0,0x71042e31b69702d1f6c0bbde0f8b99fdb484d2065496b9cf6c0702...,True,0.001,5,1.169101e+06,52152.70195,2025-12-31,2024-12-29,True,4851.465197,4.219040e+04,1.245450e+05,1.158770e+06,"[""866510513400487171880165453680059059746507712886121424...",500,5,4851.465197,4.219040e+04,1.245450e+05,1.158770e+06,1.169101e+06,52152.70195,True,False,False,False,2024-12-29T22:40:38Z,False,0.819068,False,True,100,3.5,0.010,-0.0020,-0.0090,-0.0045,0.030,0.025,0.035,True,True,False,False,[],False,False,False,False,False,16093,fed-emergency-rate-cut-in-2025,fed-emergency-rate-cut-in-2025,Fed emergency rate cut in 2025?,"This market will resolve to ""Yes"" if the Federal Open Ma...",2024-12-29T22:42:17.114047Z,2024-12-29T22:42:17.114045Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/fed...,https://polymarket-upload.s3.us-east-2.amazonaws.com/fed...,True,False,False,False,False,True,5.215270e+04,1.169101e+06,0,2024-12-29T18:06:52.829209Z,2025-11-08T19:50:04.922722Z,0.819068,4.851465e+03,4.219040e+04,1.245450e+05,1.158770e+06,True,5.215270e+04,2,"[{'id': '101588', 'label': '2025 Predictions', 'slug': '...",False,True,True,False,True,False,False,False,NaN,NaN,NaN,NaN,NaN,"[{'id': '12257', 'conditionId': '0xcddb4f52babca280f8e5f...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.0015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.03, 0.97]",[8665105134004871718801654536800590597465077128861214243...,[],2024-12-29 22:41:48.240383+00:00,2025-12-31 12:00:00+00:00,2024-12-29 18:06:53.973587+00:00,2025-11-08 19:48:40.018498+00:00,2024-12-29 22:40:38+00:00,2024-12-29 22:42:17.114047+00:00,2025-12-31 12:00:00+00:00,2024-12-29 18:06:52.829209+00:00,2025-11-08 19:50:04.922722+00:00,1.169101e+06,1.169101e+06,1.169101e+06,4851.465197,4.219040e+04,1.245450e+05,1.158770e+06,4851.465197,4.219040e+04,1.245450e+05,1.158770e+06,52152.70195,52152.70195,52152.70195,0.025,0.035,0.030,0.010,0.001,5,0.819068,100,3.5
14,516842,Brian Armstrong out as Coinbase CEO in 2025?,0x178dee952f29fb0a77f63df1d59514d15009caeb7c011a5c086aad...,brian-armstrong-out-as-coinbase-ceo-in-2025,,2025-12-31T12:00:00Z,30607.8409,2024-12-30T18:15:44.566Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/bri...,https://polymarket-upload.s3.us-east-2.amazonaws.com/bri...,"This market will resolve to ""Yes"" if Brian Armstrong is ...","[""Yes"", ""No""]","[""0.025"", ""0.975""]",171004.267994,True,False,,2024-12-30T17:12:08.910514Z,2025-11-08T19:48:27.192316Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x6A9D222616C90FcA5754cd1333cFD9b7fb6a4F74,True,Brian Armstrong - Coinbase,5,0xf3386acdbd5ca7181ac5b6ec100aae4a042618ef998a4b7d3ec240...,True,0.001,5,1.710043e+05,30607.84090,2025-12-31,2024-12-30,True,NaN,2.615512e+02,5.078032e+02,1.710043e+05,"[""973356764210952480008792367356726237278638256684464483...",500,5,NaN,2.615512e+02,5.078032e+02,1.710043e+05,1.710043e+05,30607.84090,True,False,False,False,2024-12-30T18:14:36Z,False,0.815910,False,True,50,3.5,0.008,NaN,-0.0205,-0.0555,0.020,0.021,0.029,True,True,False,False,[],False,False,False,False,False,16086,which-ceos-will-be-out-in-2025,which-ceos-will-be-out-in-2025,Which CEOs will be gone in 2025?,This is a market group over which CEOs will be out of th...,2024-12-30T18:15:53.510615Z,2024-12-30T18:15:53.51061Z,2025-12-31T12:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/whi...,https://polymarket-upload.s3.us-east-2.amazonaws.com/whi...,True,False,False,False,False,True,5.440452e+04,4.979125e+05,0,2024-12-29T17:40:52.275707Z,2025-11-08T19:50:17.692071Z,0.847009,2.999000e+02,2.538730e+03,2.637663e+04,4.979125e+05,True,5.440452e+04,8,"[{'id': '107', 'label': 'Business', 'slug': 'business', ...",False,True,True,False,True,False,False,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,False,NaN,default,False,False,NaN,ascending,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[Yes, No]","[0.025, 0.975]",[9733567642109524800087923673567262372786382566844644833...,[],2024-12-30 18:15:44.566000+00:00,2025-12-31 12:00:00+00:00,2024-12-30 17:12:08.910514+00:00,2025-11-08 19:48:27.192316+00:00,2024-12-30 18:14:36+00:00,2024-12-30 18:15:53.510615+00:00,2025-12-31 12:00:00+00:00,2024-12-29 17:40:52.275707+00:00,2025-11-08 19:50:17.692071+00:00,1.710043e+05,1.710043e+05,1.710043e+05,NaN,2.615512e+02,5.078032e+02,1.710043e+05,NaN,2.615512e+02,5.078032e+02,1.710043e+05,30607.84090,30607.84090,30607.84090,0.021,0.029,0.020,0.008,0.001,5,0.815910,50,3.5
87,574071,"Will Ethereum hit $14,000 by December 31?",0x93621441f16eda493eace04900e1323e50e0b0a93c83d8f71d9d5a...,will-ethereum-hit-14000-by-december-31-239-295,,NaN,114131.8105,2025-08-08T10:24:38.523Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/ETH...,https://polymarket-upload.s3.us-east-2.amazonaws.com/ETH...,"This market will immediately resolve to ""Yes"" if any Bin...","[""Yes"", ""No""]","[""0.015"", ""0.985""]",735475.940092,True,False,0x7f14626660aade6B8CFd3913ad723aD6D20CeCD5,2025-08-08T10:23:05.486515Z,2025-11-08T19:54:59.742709Z,False,False,0x91430CaD2d3975766499717fA0D66A78D814E5c5,False,0x157Ce2d672854c848c9b79C49a8Cc6cc89176a49,True,"$14,000",1,0x20f4b44dd40e149ff09c266fc9416eb22b7e314982647ada09f741...,True,0.001,5,7.354759e+05,114131.81050,NaN,2025-08-08,True,8881.535534,6.220677e+04,2.939807e+05,7.331278e+05,"[""103340235029917759242440988364163632161240314966392371...",500,5,8881.535534,6.220677e+04,2.939807e+05,7.331278e+05,7.354759e+05,114131.81050,True,False,False,False,2025-08-08T10:24:17Z,False,0.809569,False,True,0,0.0,0.002,NaN,-0.0005,-0.0225,0.015,0.014,0.016,True,True,False,False,[],False,False,False,False,False,16097,what-price-will-ethereum-hit-in-2025,what-price-will-ethereum-hit-in-2025,What price will Ethereum hit in 2025?,This is a market group over what prices Ethereum will hi...,2024-12-30T22:12:39.205198Z,2024-12-30T22:12:39.205193Z,2026-01-01T05:00:00Z,https://polymarket-upload.s3.us-east-2.amazonaws.com/ETH...,https://polymarket-upload.s3.us-east-2.amazonaws.com/ETH...,True,False,False,False,False,True,1.279571e+06,3.211457e+07,0,2024-12-29T18:11:49.204982Z,2025-11-08T19:50:11.596425Z,0.985804,4.406609e+05,3.918738e+06,1.131422e+07,3.091843e+07,True,1.279571e+06,2982,"[{'id': '21', 'label': 'Crypto', 'slug': 'crypto', 'forc...",False,True,False,False,True,False,False,False,NaN,NaN,NaN,NaN,,NaN,NaN,,,False,NaN,default,False,False,NaN,NaN,"[{'id': '10017', 'ticker': 'ethereum-hit-price-monthly',...",eth-monthly-prices,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2025-08-08T10:23:48.485147Z,NaN,NaN,"[Yes, No]","[0.015, 0.985]",[1033402350299177592424409883641636321612403149663923713...,[],2025-08-08 10:24:38.523000+00:00,NaT,2025-08-08 10:23:05.486515+00:00,2025-11-08 19:54:59.742709+00:00,2025-08-08 10:24:17+00:00,2024-12-30 22:12:39.205198+00:00,2026-01-01 05:00:00+00:00,2024-12-29 18:11:49.204982+00:00,2025-11-08 19:50:11.596425+00:00,7.354759e+05,7.354759e+05,7.354759e+05,8881.535534,6.220677e+04,2.939807e+05,7.331278e+05,8881.535534,6.220677e+04,2.939807e+05,7.331278e+05,114131.81050,114131.81050,114131.81050,0.014,0.016,0.015,0.002,0.001,5,0.809569,0,0.0